# Generated by wellwell theme builder

# Load fzf key-bindings & completion
if command -v brew >/dev/null 2>&1; then
  __FZF_PREFIX="$(brew --prefix)/opt/fzf"
  [ -f "$__FZF_PREFIX/shell/key-bindings.zsh" ] && source "$__FZF_PREFIX/shell/key-bindings.zsh"
  [ -f "$__FZF_PREFIX/shell/completion.zsh" ] && source "$__FZF_PREFIX/shell/completion.zsh"
elif command -v fzf >/dev/null 2>&1; then
  # Common locations for the upstream install script
  for __fzf_dir in "$HOME/.fzf" "/usr/share/doc/fzf/examples" "/usr/share/fzf"; do
    [ -f "$__fzf_dir/key-bindings.zsh" ] && source "$__fzf_dir/key-bindings.zsh"
    [ -f "$__fzf_dir/completion.zsh" ] && source "$__fzf_dir/completion.zsh"
  done
fi
unset __FZF_PREFIX __fzf_dir

# Preview
export FZF_PREVIEW_COMMAND='(bat --style=numbers --color=always --line-range=:200 {} || batcat --style=numbers --color=always --line-range=:200 {} || true) || eza --tree --level=2 --color=always {}'
export FZF_CTRL_T_OPTS='--preview "$FZF_PREVIEW_COMMAND"'
export FZF_CTRL_T_COMMAND='fd --type f --hidden --follow --exclude .git'

# UI defaults
export FZF_DEFAULT_OPTS='
  --border --height=80% --layout=reverse --info=inline-right
  --color=fg:-1,fg+:#ffffff,bg:-1,bg+:#373737,hl:#007ACC,hl+:#33adff,info:#afaf87,marker:#6A9955
  --color=prompt:#C586C0,spinner:#C586C0,pointer:#C586C0,header:#569CD6,border:#525252,label:#929292,query:#929292,gutter:-1
  --prompt="❯❯ " --marker=">" --pointer="*" --separator="" --scrollbar="│"'
