# Generated by wellwell theme builder

# Load fzf key-bindings & completion from Homebrew if available
if command -v brew >/dev/null 2>&1; then
  __FZF_PREFIX="$(brew --prefix)/opt/fzf"
  [ -f "$__FZF_PREFIX/shell/key-bindings.zsh" ] && source "$__FZF_PREFIX/shell/key-bindings.zsh"
  [ -f "$__FZF_PREFIX/shell/completion.zsh" ] && source "$__FZF_PREFIX/shell/completion.zsh"
fi
unset __FZF_PREFIX

# Preview
export FZF_PREVIEW_COMMAND='bat --style=numbers --color=always --line-range=:200 {} || eza --tree --level=2 --color=always {}'
export FZF_CTRL_T_OPTS='--preview "$FZF_PREVIEW_COMMAND"'
export FZF_CTRL_T_COMMAND='fd --type f --hidden --follow --exclude .git'

# UI defaults
export FZF_DEFAULT_OPTS='
  --border --height=80% --layout=reverse --info=inline-right
  --color=fg:-1,fg+:#ffffff,bg:-1,bg+:#373737,hl:#7c3aed,hl+:#af6dff,info:#afaf87,marker:#16a34a
  --color=prompt:#f97316,spinner:#f97316,pointer:#f97316,header:#06b6d4,border:#617085,label:#a1b0c5,query:#a1b0c5,gutter:-1
  --prompt="❯❯ " --marker=">" --pointer="*" --separator="" --scrollbar="│"'
